language: java
jdk:
  - openjdk8
branches:
  only:
    - master
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a534fbf2d70b49f104e6
    on_success: change
    on_failure: always
    on_start: never
