name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - bugfix/**
      - feature/**

jobs:
  build_node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18, 20 ]
    name: Build frontend with Node ${{ matrix.node }}
    defaults:
      run:
        working-directory: src/main/webapp
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: 'src/main/webapp/package-lock.json'
      - run: npm ci
      - run: npm run-script build
  
  build_maven:
    name: Build backend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: maven
    - name: Build with Maven without frontend
      run: mvn -B package -P!webapp --file pom.xml
